# Generated by Django 5.1.1 on 2024-09-23 10:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20240920_1922'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profilephoto',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profilephoto',
            name='photo',
            field=models.ImageField(error_messages={'invalid_extension': 'This file do not supported!'}, upload_to='files/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'gif', 'png'))]),
        ),
    ]
