# Generated by Django 5.1.1 on 2025-04-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_alter_profilephoto_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='attempts',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='testresult',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testresult',
            name='time_spent',
            field=models.FloatField(default=0.0),
        ),
    ]
